### ISSUE TITLE
#11: YagptUtility

### ISSUE THREAD

**Issue by divramod** [divramod/yagpt#11]
# TODO
- [ ] look if ya is run in subdirectory code
- [ ] make yagpt usable programatically
- [ ] move zsh aliases to yagpt/config
