### ISSUE TITLE
#12: DashboardUtility

### ISSUE THREAD

**Issue by divramod** [divramod/yagpt#12]
# SUMMARY
I want to use the tool like lazygit.

# TODO
- research (#22)
  - [ ] test chalk.js
  - [ ] test vorpahl.js
  - [ ] test robot js
- [ ] prepare (#22)
  - [ ] write stack overflow question on how to best test cli nodejs tools
- add design (#22)
  - [ ] make picture of S. 134

# DONE
