### ISSUE TITLE
#3: Documentation

### ISSUE THREAD

**Issue by divramod** [divramod/yagpt#3]
# TODO
- [ ] move repository to github (can i use the issues there?)
- [ ] install typedoc github plugin
- [ ] add typedoc rerun after change to yagpt test tmux pane
- [ ] add snippets for commentRun commentIsRunnable commentClass commentFunction commentDescribe commentIt
- [ ] move design decisions into own files
- [ ] add styleguide

# DONE
## add design decisions to README.md (#20)
