### ISSUE TITLE
#4: LoggerUtility

### ISSUE THREAD

**Issue by divramod** [divramod/yagpt#4]
# TODO
## remove UTask/rename to ULogger (#4)
- [ ] add logger (mv logValue from task to logger)
- [ ] move things which log into new function yLogger
- [ ] refactore all influenced lines of code
- [ ] 100% test coverage
