### ISSUE TITLE
#5: TestUtility

### ISSUE THREAD

**Issue by divramod** [divramod/yagpt#5]
# ToDo

## UTest (#31)
- [ ] add function UTest.createDirectory which checks, if in test path (rename only)
- [ ] add function UTest.deleteDirectory which checks, if in test path
- [ ] add function UTest.deleteFile which checks, if in test path
- [ ] rename UTest.createTestFile to createFile (checks path)

## document/refactore UTest (#31)
- [ ] UTest.testPath vs UConfig.testPath (where to place this?)
- [ ] UTest.prepareNpmRepository or UNpm.prepareNpmRepository (it belongs only to testing, for production one can use copyOrCloneRepository()
- [ ] UTest add function which prints out filename from src (removes everything before) --> for easier seeing what the path is
- [ ] add function to all describe blocks
- [ ] document/refactore all functions
- [ ] 100% test coverage
