### ISSUE TITLE
#6: PromptUtility

### ISSUE THREAD

**Issue by divramod** [divramod/yagpt#6]
# Summary
As a developer i want to have the 6 szenarios running.

# TODO
- [ ] refactor out the work from the main index file into a 
- [ ] path.1 run job from path
- [ ] path.2 run prompt from path
- [ ] path.3 return path not existant
- [ ] no-path.1 run prompt from current directory jobs
- [ ] no-path.2 run prompt for business, when business.json is existant
- [ ] no.path.3 no jobs dir/no business.json but package.json
- [ ] no.path.4 no jobs dir/no business.json/no package.json but is git
- [ ] remove jobs in path?
  - [ ] a prompt is a submenu when no index.ts is existant
- [ ] seperate between package path and project path
- [ ] look for project part in package.json
- [ ] add test for
  - [ ] with path set
  - [ ] without path set

# DONE
