### ISSUE TITLE
#8: CiUtility

### ISSUE THREAD

**Issue by divramod** [divramod/yagpt#8]
# SUMMARY
As a developer i want to have every tool in my toolset. CI is last part, so i need it!

# TODO
- [ ] set up a ci tool
- [ ] create a ci cycle
- [ ] implement stages (testing/development/production)
- [ ] read https://hackernoon.com/continuous-integration-circleci-vs-travis-ci-vs-jenkins-41a1c2bd95f5
- [ ] rr: tox
- [ ] research different tools (travis, jenkins, circle)
- [ ] job.gitflow create release
  - [ ] add build step (make use of src and dist)
- [ ] run with hook
- [ ] rr: https://www.npmjs.com/package/ci-publish (gitlab hook)
