### ISSUE TITLE
#9: DebuggerUtility

### ISSUE THREAD

**Issue by divramod** [divramod/yagpt#9]
# SUMMARY
I want to be able to debug profossionally.

# TODO
- [ ] find importing bug
- [ ] try GoogleChromeLabs ndb
- [ ] install np
- [ ] try to find reason for bug

# DONE
